name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        echo "Hello, Joe!"
        pwd
        ls
        node --version
        npm install sfdx-cli --global
        sfdx --version
